### ISSUE TITLE
Use css instead of scss for center() and column()

### ISSUE THREAD

**Issue by ghost** [akiran/reddit-clone#2]
I am porting reddit-clone to use css instead of scss. I am not understanding, how to write the equivalent css code for,

``` scss
  /*_sidebar.scss  */
  @include column(1/3);
  /* _header.scss */
  @include center();
```

On the net, it says, @include is a mixin to import rules into the current element. If so, where are the rules, column and center defined inside this project? 
What is the css code for these lines?

**Comment by akiran** [comment]
If you run 

```
gulp sass
```

css will be generated in `build/css`
You can look at that code

**Comment by ghost** [comment]
that works, thanks Kiran...
